import Head from "next/head";
import Image from "next/image";
import { Button, Grid, Box, Typography } from "@mui/material";
import { FiArrowRightCircle } from "react-icons/fi";
import Navbar from "../components/Navbar";
import Banner1Img from "../public/home/banner/1.jpeg";

export default function Home() {
  return (
    <div>
      <Head>
        <title>E-commerce App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Grid
          container
          direction="row"
          justifyContent="flex-end"
          alignItems="center"
        >
          <Grid item xs={6} style={{ textAlign: "center" }}>
            <Image
              src={Banner1Img}
              alt="Picture of the author"
              // width={500}
              // height={500}
              blurDataURL={Banner1Img}
              // Optionally allows to add a blurred version of the image while loading
              placeholder="blur"
            />
          </Grid>
          <Grid item xs={6}>
            <Box
              component="div"
              justifyContent="center"
              container
              alignItems="center"
              style={{ display: "flex", flexDirection: "column" }}
            >
              <Typography variant="h5">Best in the world</Typography>
              <Typography variant="h2">Lorem10</Typography>
              <Typography variant="subtitle1">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Blanditiis, unde.
              </Typography>
              <Box mt={2}>
                <Button color="primary" variant="outlined">
                  Shop Now &nbsp;
                  <FiArrowRightCircle />
                </Button>
              </Box>
            </Box>
          </Grid>
        </Grid>
      </main>
    </div>
  );
}
