import Head from "next/head";
// import Image from "next/image";
// import { Button, Grid, Box, Typography } from "@mui/material";
// import { FiArrowRightCircle } from "react-icons/fi";
import Navbar from "../components/Navbar";
import Banner1Img from "../public/home/banner/1.jpeg";
import styles from "./index.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Glizzy Test App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <Navbar />
        <section className={styles.banner}>
          <div className="container">
            <div className="row">
              <div className="col-md-6">
                <h3>asdfasdf</h3>
                <h4>asdfasdfasf asdf asdf asdf</h4>

                <form action="">
                  <input type="text" className="form-contorl" />
                </form>
                <span>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Explicabo, quod?
                </span>
                <div>
                  <button className="btn btn-circle btn-primary" type="button">
                    asdfasdf
                  </button>
                  <button className="btn btn-circle btn-primary" type="button">
                    asdfasdf
                  </button>
                  <button className="btn btn-circle btn-primary" type="button">
                    asdfasdf
                  </button>
                  <button className="btn btn-circle btn-primary" type="button">
                    asdfasdf
                  </button>
                </div>
              </div>
              <div className="col-md-6">
                <img
                  src="https://images.pexels.com/photos/3756879/pexels-photo-3756879.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
                  alt="Picture of the author"
                  // blurDataURL={Banner1Img}
                  // placeholder="blur"
                  className="img img-fluid"
                />
              </div>
            </div>
          </div>
        </section>
        {/* <Grid
          container
          direction="row"
          justifyContent="flex-end"
          alignItems="center"
        >
          <Grid item xs={6} style={{ textAlign: "center" }}>
            <Image
              src={Banner1Img}
              alt="Picture of the author"
              blurDataURL={Banner1Img}
              placeholder="blur"
            />
          </Grid>
          <Grid item xs={6}>
            <Box
              component="div"
              justifyContent="center"
              container
              alignItems="center"
              style={{ display: "flex", flexDirection: "column" }}
            >
              <Typography variant="h5">Best in the world</Typography>
              <Typography variant="h2">Lorem10</Typography>
              <Typography variant="subtitle1">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Blanditiis, unde.
              </Typography>
              <Box mt={2}>
                <Button color="primary" variant="outlined">
                  Shop Now &nbsp;
                  <FiArrowRightCircle />
                </Button>
              </Box>
            </Box>
          </Grid>
        </Grid> */}
      </main>
    </div>
  );
}
